#!/bin/sh
echo "### set work directory ###"
multipass exec sdx -- bash -c "sudo mkdir /var/lib/kytos"
multipass exec sdx -- bash -c "sudo mkdir /var/run/kytos"
multipass exec sdx -- bash -c "sudo mkdir /var/tmp/kytos"
multipass exec sdx -- bash -c "sudo mkdir /etc/kytos"
multipass exec sdx -- bash -c "sudo mkdir -p /usr/src/kytos"
multipass exec sdx -- bash -c "sudo chown ubuntu:ubuntu /usr/src/kytos"
multipass exec sdx -- bash -c "cd /usr/src/kytos && git clone https://github.com/kytos-ng/python-openflow"
multipass exec sdx -- bash -c "cd /usr/src/kytos && git clone https://github.com/kytos-ng/kytos-utils"
multipass exec sdx -- bash -c "cd /usr/src/kytos && git clone https://github.com/kytos-ng/kytos"
multipass exec sdx -- bash -c "cd /usr/src/kytos && git clone https://github.com/kytos-ng/flow_manager"
multipass exec sdx -- bash -c "cd /usr/src/kytos && git clone https://github.com/kytos-ng/mef_eline"
multipass exec sdx -- bash -c "cd /usr/src/kytos && git clone https://github.com/kytos-ng/of_core"
multipass exec sdx -- bash -c "cd /usr/src/kytos && git clone https://github.com/kytos-ng/of_lldp"
multipass exec sdx -- bash -c "cd /usr/src/kytos && git clone https://github.com/kytos-ng/pathfinder"
multipass exec sdx -- bash -c "cd /usr/src/kytos && git clone https://github.com/kytos-ng/topology"
multipass exec sdx -- bash -c "cd /usr/src/kytos && git clone https://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@github.com/atlanticwave-sdx/kytos-sdx-topology sdx_topology"
