#!/bin/sh
echo "### set mininet ###"
multipass exec sdx -- bash -c "sudo mn --version"
multipass exec sdx -- bash -c "sudo mn --switch ovsbr --test pingall"
multipass exec sdx -- bash -c "echo 'deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /' | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list"
multipass exec sdx -- bash -c "curl -L 'https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/Release.key' | sudo apt-key add -"
multipass exec sdx -- bash -c "sudo bash -c 'echo 1 > /proc/sys/net/ipv4/ip_forward'"
echo "### set kytos & napps ###"
multipass exec sdx -- bash -c "sudo mkdir /var/lib/kytos"
multipass exec sdx -- bash -c "sudo mkdir /var/run/kytos"
multipass exec sdx -- bash -c "sudo mkdir /var/tmp/kytos"
multipass exec sdx -- bash -c "sudo mkdir /etc/kytos"
multipass exec sdx -- bash -c "sudo mkdir -p /usr/src/kytos"
multipass exec sdx -- bash -c "sudo chown ubuntu:ubuntu /usr/src/kytos"
multipass exec sdx -- bash -c "cd /usr/src/kytos && git clone https://github.com/kytos-ng/python-openflow"
multipass exec sdx -- bash -c "cd /usr/src/kytos/python-openflow && python3 setup.py develop"
multipass exec sdx -- bash -c "cd /usr/src/kytos && git clone https://github.com/kytos-ng/kytos-utils"
multipass exec sdx -- bash -c "cd /usr/src/kytos/kytos-utils && python3 setup.py develop"
multipass exec sdx -- bash -c "cd /usr/src/kytos && git clone https://github.com/kytos-ng/kytos"
multipass exec sdx -- bash -c "cd /usr/src/kytos/kytos && python3 setup.py develop"
multipass exec sdx -- bash -c "cd /usr/src/kytos && git clone https://github.com/kytos-ng/flow_manager"
multipass exec sdx -- bash -c "cd /usr/src/kytos/flow_manager && python3 setup.py develop"
multipass exec sdx -- bash -c "cd /usr/src/kytos && git clone https://github.com/kytos-ng/mef_eline"
multipass exec sdx -- bash -c "cd /usr/src/kytos/mef_eline && python3 setup.py develop"
multipass exec sdx -- bash -c "cd /usr/src/kytos && git clone https://github.com/kytos-ng/of_core"
multipass exec sdx -- bash -c "cd /usr/src/kytos/of_core && python3 setup.py develop"
multipass exec sdx -- bash -c "cd /usr/src/kytos && git clone https://github.com/kytos-ng/of_lldp"
multipass exec sdx -- bash -c "cd /usr/src/kytos/of_lldp && python3 setup.py develop"
multipass exec sdx -- bash -c "cd /usr/src/kytos && git clone https://github.com/kytos-ng/pathfinder"
multipass exec sdx -- bash -c "cd /usr/src/kytos/pathfinder && python3 setup.py develop"
multipass exec sdx -- bash -c "cd /usr/src/kytos && git clone https://github.com/kytos-ng/topology"
multipass exec sdx -- bash -c "cd /usr/src/kytos/topology && python3 setup.py develop"
multipass exec sdx -- bash -c "cd /usr/src/kytos && git clone https://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@github.com/atlanticwave-sdx/kytos-sdx-topology sdx_topology"
multipass exec sdx -- bash -c "cd /usr/src/kytos/sdx_topology && python3 setup.py develop"
